---
- name: Creating user roles and database
  hosts: all
  tasks:
  - name: Connect to default database and create a user with super prvileges
    postgresql_user:
      name: dbadmin
      password: dbadmin1234
      role_attr_flags: CREATEDB,SUPERUSER,CREATEROLE,LOGIN
  - name: Create a new database with name "testdatabase"
    postgresql_db:
      login_host: 192.168.1.31
      login_user: dbadmin
      login_password: dbadmin1234
      port: 5432
      name: testdatabase